# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    schedule:
      interval: "weekly"
    
    # Use conventional commits
    commit-message:
      prefix: "chore"
      include: "scope"
      
    # Group all dependency updates into a single PR to reduce noise
    groups:
      all-dependencies:
        patterns:
          - "*"
          
    # Limit number of open PRs
    open-pull-requests-limit: 5